### ISSUE TITLE
CAN-SPAM Compliance

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail-kb#10]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ comment-mail.com<br />:page_with_curl: See: [CAN-SPAM Compliance](http://comment-mail.com/kb-article/can-spam-compliance/)
[:octocat: View Markdown File](https://github.com/websharks/comment-mail-kb/blob/master/tutorials/2015/10-can-spam-compliance.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/comment-mail-kb/edit/master/tutorials/2015/10-can-spam-compliance.md)

---

**Comment by jaswsinc** [comment]
This article should also detail the way Comment Mail automatically attaches an unsubscribe link to every email that it sends.

**Comment by raamdev** [comment]
I suggest not blockquoting the list underneath "Among other things, the CAN-SPAM Act requires that:"; those points seem like one of the primary pieces of the article and they look greyed out (because they're in blockquotes).

**Comment by jaswsinc** [comment]
Done. Thanks! :-)

**Comment by kristineds** [comment]
@jaswsinc @raamdev Is this article still relevant even if references to "CAN-SPAM Act" had been removed from the plugin? Referencing: https://github.com/websharks/comment-mail/issues/122

If yes, maybe we could update the instructions on the article? Currently it says this (title on the panel has been changed):

_On the article:_
![screen shot 2016-02-12 at 12 59 24 pm](https://cloud.githubusercontent.com/assets/7514953/12999349/155533c0-d189-11e5-94cd-ebbbb6072d3e.png)

_What we have on the plugin now:_
![screen shot 2016-02-12 at 12 58 31 pm](https://cloud.githubusercontent.com/assets/7514953/12999351/17e68436-d189-11e5-9382-3e5e60addfc4.png)

**Comment by raamdev** [comment]
@kristineds Yes, this article is still relevant, however we do need to update the screenshots and the text to reference the new name of his panel ("Postmaster / Contact Info").

**Comment by kristineds** [comment]
@jaswsinc @raamdev I updated the text (should say "Postmaster / Contact Info") and the screenshot on the site. https://github.com/websharks/comment-mail-kb/commit/783e07cd4ad6e46e97f3de5c5a801d621919feb2

- http://comment-mail.com/kb-article/can-spam-compliance/

**Comment by jaswsinc** [comment]
Cool :-)

**Comment by raamdev** [comment]
@kristineds I reviewed this. Thank you!

For future reference, you may want to try to keep your email address out of screenshots that will be posted publicly--I usually use `example@example.com` or something like that. No big deal, but I thought I'd point it out. :-)

**Comment by kristineds** [comment]
> you may want to try to keep your email address out of screenshots that will be posted publicly

@jaswsinc Copy that. Will keep that in mind. :)  I updated that screenshot. http://comment-mail.com/kb-article/can-spam-compliance/
