### ISSUE TITLE
Can existing users add new subscriptions without commenting?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#31]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
toc-enable: off
title: Can users manage their own subscriptions?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/31
```
---

Yes, subscribers can add their own subscriptions and can subscribe to any comment without actually commenting. First, please make sure you have enabled the "Comment Form Subscriber Options Template". Please see: **Dashboard → Comment Mail → Config Options → Comment Form → Enable Comment Form Subscr. Options Template?**

On the front-end, when clicking "Reply", the link to "Subscribe without Commenting" will be available. This will allow the visitor to access the **Add New Subscription** page where they can create a new comment subscription.

![leavereply](https://user-images.githubusercontent.com/13220018/27345893-d910a528-561d-11e7-82a8-a0d0c33f749f.png)

From the Add New Subscription page, they can then add and customize their subscriptions from a number of different options such as: the specific Post they wish to subscribe to, specific Comments/ Comment Threads / Replies or even All Comments/Replies, and even how often they receive notifications for updates.

### Adding New Subscriptions

![add new](https://user-images.githubusercontent.com/13220018/27346098-9f3340a8-561e-11e7-9bd8-4d0a8026ac67.png)

![choose comment](https://user-images.githubusercontent.com/13220018/27346251-251bbca4-561f-11e7-90e6-34be294d3c0c.png)

![delivery method](https://user-images.githubusercontent.com/13220018/27346417-bad0b1dc-561f-11e7-8f20-01caa37618dd.png)

**Comment by renzms** [comment]
@raamdev Please check thanks!

**Comment by raamdev** [comment]
This doesn't really seem to answer the question in the title. Also, the screenshot is for "Add New Subscription" and does not show any list of subscriptions being managed.

**Comment by renzms** [comment]
@raamdev 

Hi Raam, you're right the original message of the article was unclear. Instead I overhauled this draft article by adding the right content _here_ for managing and modifying subscriptions: [Can members modify their existing subscriptions?](https://github.com/websharks/comment-mail-kb/issues/40)

Then I made this current draft an extension of [Can visitors subscribe without commenting?](https://github.com/websharks/comment-mail-kb/issues/30), and showcased how an existing user/subscriber could add new subscriptions without commenting.

Please check thanks!

**Comment by raamdev** [comment]
Feedback:

- "front end" should be "front-end".
- "`Reply`, the **link** to" — Please don't use code style for button labels or menus. This should be "'Reply', the link to".
- "the link to Subscribe without Commenting will be available." — I would add another sentence to the end of that to help introduce the next section: "This will allow the visitor to access the **Add New Subscription** page where they can create a new comment subscription."
- Change the bold text above screenshots to H3's.

**Comment by renzms** [comment]
@raamdev 

Changed:

- [x] "front end" should be "front-end".
- [x] "Reply, the link to" — Please don't use code style for button labels or menus. This should be "'Reply', the link to".
- [x] "the link to Subscribe without Commenting will be available." — I would add another sentence to the end of that to help introduce the next section: "This will allow the visitor to access the Add New Subscription page where they can create a new comment subscription."
- [x] Change the bold text above screenshots to H3's.
- [x]  Updated Screenshots

Ready for check, thanks!

**Comment by raamdev** [comment]
The screenshots look much better, but there are still a few issues with them:

- [ ] Most of them look slightly blurry to me—I'm not sure why. Is the resolution too low? 
- [ ] The jagged border and the shadow are too harsh (too dark), so they detract the eyes away from the screenshot itself and make you want to stare at the border instead. See this screenshot I just made and compare it to yours:

![2017-06-19_18-50-32](https://user-images.githubusercontent.com/53005/27309100-2f46fe28-5520-11e7-8c7a-e484814099fb.png)

- [ ] The first screenshot with "Subscribe without commenting" highlighted could really use a red arrow pointing to that highlighted text, just because the highlighted text is still a bit hard to notice when there's so much other stuff in the screenshot.

**Comment by renzms** [comment]
@raamdev 

Updated screens! Thanks :)

**Comment by raamdev** [comment]
> There they can add and customize their subscriptions

Reiterate where "There" is (e.g., "From the **Add New Subscription** page, they can add and customize..."

> Adding New Subscriptions

Remove the headers above the screenshots here; those aren't necessary since the screenshots already contain headers and there's no text in between the screenshots.

> On the front-end, when clicking 'Reply', the **link** to Subscribe without Commenting will be available.

'Reply' should be double-quoted as "Reply". "link" should not be bold here. "Subscribe without Commenting" should be double-quoted.

> make sure you have enabled the Comment Form Subscribers Options Template

"Comment Form Subscribers Options Template" should be double-quoted. "Subscribers" should be "Subscriber".

**Comment by renzms** [comment]
There they can add and customize their subscriptions

- [ ] Reiterate where "There" is (e.g., "From the Add New Subscription page, they can add and customize..."

Adding New Subscriptions

- [ ] Remove the headers above the screenshots here; those aren't necessary since the screenshots already contain headers and there's no text in between the screenshots.

On the front-end, when clicking 'Reply', the link to Subscribe without Commenting will be available.

- [ ] 'Reply' should be double-quoted as "Reply". "link" should not be bold here. "Subscribe without Commenting" should be double-quoted.

make sure you have enabled the Comment Form Subscribers Options Template

- [ ] "Comment Form Subscribers Options Template" should be double-quoted. "Subscribers" should be "Subscriber".

**Comment by renzms** [comment]
@raamdev 

Updated with corrections, please check. Thanks! :)
